project:
  type: website
  title: "Scientific Instrumentation"
  output-dir: docs
  render:
    - "*.qmd"
  resources:
    - "Instrumentation/*.qmd"
    - "MetaCategory/*.qmd"
  preview:
    browser: false

format:
  html:
#    respect-user-color-scheme: true
    theme: 
      light: flatly
      dark: darkly
    font-size: medium


website:
# Puts it below the TOC. Using "Tools" instead for GitHub links.
# repo-url: https://github.com/The-Evergreen-State-College/Scientific-Instrumentation
# repo-actions: [source, issue]
  announcement:
    icon: info-circle
    dismissable: true
    content: "**INFORMATIONAL NOTICE:** This site is under active development!"
    type: primary
    position: below-navbar
  back-to-top-navigation: true
  page-footer: "In pursuit of scientific inquiry."
  reader-mode: true
  page-navigation: true
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: "index.qmd"
      - text: "Meta-Categories" 
        menu:
          - text: "NIST-2024"
            href: "MetaCategory/NIST-2024.qmd"
          - text: "Chromatography"
            href: "MetaCategory/Chromatography.qmd"
          - text: "Data Loggers"
            href: "MetaCategory/DataLoggers.qmd"
          - text: "Imaging"
            href: "MetaCategory/Imaging.qmd"
          - text: "Microscopy"
            href: "MetaCategory/Microscopy.qmd"
          - text: "Spectroscopy"
            href: "MetaCategory/Spectroscopy.qmd"   
          - text: "Unmanned Vehicle Systems (UVS)"
            href: "MetaCategory/UnmannedVehicleSystems.qmd"                   
          - text: "Other"
            href: "MetaCategory/Other.qmd"
      - text: "Instruments" 
        menu:
          - text: "Agilent Cary 60 UV-Vis"
            href: "Instrumentation/Agilent-Cary-60-UV-Vis.qmd"            
          - text: "Agilent Cary 3500 UV-Vis Flexible"
            href: "Instrumentation/Agilent-Cary-3500-UV-Vis-Flexible.qmd"        
          - text: "Agilent ICP-MS 7850"
            href: "Instrumentation/Agilent-ICP-MS-7850.qmd"
          - text: "Blue Robotics BlueROV2"
            href: "Instrumentation/BlueRobotics-ROV-BlueROV2.qmd"
          - text: "Bruker Avance 400 MHz NMR"
            href: "Instrumentation/Bruker-Avance-400MHz-NMR.qmd"
          - text: "GOWMAC 400"
            href: "Instrumentation/GOWMAC-400.qmd"
          - text: "Instron 34SC-1"
            href: "Instrumentation/Instron-34SC-1.qmd"
          - text: "Leica M205 FCA Microscope"
            href: "Instrumentation/Leica-M205-FCA-Microscope.qmd"  
          - text: "Molecular Devices SpectraMax iD3 Microplate Reader"
            href: "Instrumentation/Molecular-Devices-SpectraMax-iD3-Microplate-Reader.qmd"
          - text: "PerkinElmer FI-IR Spectrum Two" 
            href: "Instrumentation/PerkinElmer-FTIR-Spectrum-Two.qmd"
          - text: "PerkinElmer FT-IR Microscopy System Spotlight 200 with Spectrum Two"
            href: "Instrumentation/PerkinElmer-FTIR-Microscopy-System-Spotlight-200.qmd"
          - text: "SEAL AQ 300"
            href: "Instrumentation/SEAL-AQ-300-Discrete_Analyzer.qmd"
          - text: "TESCAN CLARA SEM"
            href: "Instrumentation/TESCAN-CLARA-SEM.qmd"
          - text: "YSI EXO1 Sonde"
            href: "Instrumentation/YSI-EXO1-Sonde.qmd"  
      - text: "Logbooks"
        menu:
          - text: "Index"
            href: "Instrumentation/Logbooks.qmd"
          - text: "Disaster Recovery"
            href: "Instrumentation/Disaster_Recovery_Table.qmd"
    tools:
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/The-Evergreen-State-College/Scientific-Instrumentation
          - text: Submit ticket
            href: https://github.com/The-Evergreen-State-College/Scientific-Instrumentation/issues
execute:
  freeze: auto
  cache: true